// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    CreateReview: typeof import('./src/components/CreateReview.vue')['default']
    ReviewDetail: typeof import('./src/components/ReviewDetail.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Wallet: typeof import('./src/components/Wallet.vue')['default']
  }
}
